services:
  app:
    build: .
    volumes:
      - appdata:/app/data
    environment:
      - DATA_DIR=/app/data
    env_file: .env
    ports:
      - "${PORT:-5000}:${PORT:-5000}"

volumes:
  appdata:
